[travis] Add test for extraneous blank lines at the end of files

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,6 +7,7 @@ env:
   - BUILD_TYPE=make      # build using Makefile
   - BUILD_TYPE=complete  # build manually and regenerate figures, grammar, and cross-references
   - BUILD_TYPE=check-whitespace  # check for whitespace at the ends of lines
+  - BUILD_TYPE=check-newlines  # check for blank lines at the ends of files
 
 script:
   # Build std.pdf
@@ -37,6 +38,10 @@ script:
   # Fail if there is whitespace at the ends of any lines
   - if [ "$BUILD_TYPE" = "check-whitespace" ]; then
       ! grep '\s$' source/*.tex;
+    fi
+  # Fail if there are blank lines at the ends of any files
+  - if [ "$BUILD_TYPE" = "check-newlines" ]; then
+      for f in source/*.tex; do [ $(tail -c 2 $f | wc -l) -eq 1 ] || exit 1; done;
     fi
   # Check to see if generated files are out-dated
   - pushd source
